### ISSUE TITLE
Investigate UDG option

### ISSUE THREAD

**Issue by apeltzer** [Integrative-Transcriptomics/DamageProfiler#13]
Maybe we could include a switch to have a plot for UDG treated data as well and have this in the plot as well.  Is this even desirable?

**Comment by JudithNeukamm** [comment]
I'm not sure I understand what you mean. Why should it be of interest to plot a flat line? Or in other words, there's no problem with plotting UDG treated data. Why should we need an option for that?

**Comment by apeltzer** [comment]
Yes, it doesn't make sense and I don't know what I wrote back then. Must have been my PhD writing times with lots of crap in my head.
