### ISSUE TITLE
No output when choosing the option '--all_mapped_reads'

### ISSUE THREAD

**Issue by alexhbnr** [Integrative-Transcriptomics/DamageProfiler#24]
When running DamageProfiler (v0.4.4) with the option `--all_mapped_reads` and keeping all other options as set by default, DamageProfiler is not able to produce is any output. The end of the log file looks like this:

> 2019-03-06 14:42:56 INFO  StartCalculations:108 - 0 Reads processed.
> 2019-03-06 14:42:56 INFO  StartCalculations:108 - 0 Reads processed.
> 2019-03-06 14:42:56 INFO  StartCalculations:108 - 0 Reads processed.
> 2019-03-06 14:42:56 INFO  StartCalculations:108 - 0 Reads processed.
> 2019-03-06 14:42:56 INFO  StartCalculations:952 - Values normalized ....
> 2019-03-06 14:42:56 INFO  StartCalculations:126 - -------------------
> 2019-03-06 14:42:56 INFO  StartCalculations:127 - # reads used for damage calculation: 0
> 2019-03-06 14:42:56 WARN  StartCalculations:333 - No reads processed. Can't create any output
> 2019-03-06 14:42:56 INFO  StartCalculations:276 - Runtime of Module was: 3 seconds.

When running the same file with the same options but `--all_mapped_reads`, DamageProfiler runs through smoothly and is able to produce all other output files.

**Comment by JudithNeukamm** [comment]
Can you send me the beginning of the header of your bam/sam entry? I think that's the problem.

**Comment by alexhbnr** [comment]
Here are the header lines without the `@PG` tags.

`@HD     VN:1.5  SO:coordinate`
`@SQ     SN:MT   LN:16569`
`@RG     ID:I0071        SM:I0071        PL:illumina`

Is this what you were looking for?

**Comment by JudithNeukamm** [comment]
Sorry, my fault. I mean the beginning of the SAM entry. The option --all_mapped_reads only considers reads starting with 'M_'. I think your entries start differently and therefore zero reads are processed.

**Comment by alexhbnr** [comment]
OK, this makes sense then. My reads indeed don't start with "M_". It might be worth mentioning this in the help text or just read over it.
