### ISSUE TITLE
Read CRAM input

### ISSUE THREAD

**Issue by apeltzer** [Integrative-Transcriptomics/DamageProfiler#26]
As this uses the htsjdk already, it should support CRAM as input format. I'll add the required options, the reference option is already implemented here already ;-) 

x-ref: https://github.com/nf-core/eager/issues/181

**Comment by JudithNeukamm** [comment]
Hi Alex, 
how urgent is this? 
What do you mean with the 'reference option'?

**Comment by apeltzer** [comment]
Too long ago so I don#t know what I meant with this :-D 

Urgent not so much, but we might add support for nf-core/eager to generate /output CRAM instead of BAM soonish, so then it would be beneficial to have direct support for CRAM in DamageProfiler to save conversion time 👍 

As you use the htsjdk already as a library, it shouldn't require a lot actually to add this - probably 1-2 lines ...?

**Comment by JudithNeukamm** [comment]
True :) It Is implemented now and will be available with the next release.
