### ISSUE TITLE
DamageProfiler fails when having ambiguous bases in MD tag

### ISSUE THREAD

**Issue by alexhbnr** [Integrative-Transcriptomics/DamageProfiler#31]
I encountered the following problem when there is a ambiguous base in the hg19 reference sequence (e.g. M, R etc.) and the alignment was performed using BWA aln. The HTSJDK throws an expection because of an illegal MD tag for a given CIGAR string and stops.

Here is an example:
>Exception in thread "main" htsjdk.samtools.SAMException: Illegal MD pattern: 29C12M10G41 for read D00829_0273_BCDN29ANXX_PEdi_BN_MG_LL:2:1110:15407:100972 with CIGAR 95M
>    at htsjdk.samtools.util.SequenceUtil.makeReferenceFromAlignment(SequenceUtil.java:839)
>       at calculations.DamageProfiler.processRecord(DamageProfiler.java:218)
>       at calculations.DamageProfiler.handleRecord(DamageProfiler.java:154)
>       at calculations.DamageProfiler.extractSAMRecords(DamageProfiler.java:111)
>       at calculations.StartCalculations.start(StartCalculations.java:271)
>       at RunDamageProfiler.main(RunDamageProfiler.java:36)

As far as I understand is that there is a difference how the NM value is treated between HTSJDK and htslib (https://github.com/samtools/samtools/issues/717#issuecomment-325109604). HTSJDK has a non-symmetric implementation, whether two different bases are considered a mismatch, which is different from htslib. In the above case, both BWA and samtools consider the ambiguous base in 29C12**M**10G41 as a mismatch and assign the NM value to 3. For HTSJDK, the **M** is not a mismatch given the sequenced base and therefore the NM value is 2. However, if the NM tag is 2 and there are 3 non-digit characters in the MD tag while the CIGAR string has no insertion or deletion, then HTSJDK treats it as a violation of the SAM format.

While I guess, there is no easy fix within DamageProfiler, do you guys know how to get DamageProfiler running on such read data? I tried `samtools calmd` and `picard SetNmMdAndUqTags`, however, neither of them solved the issue. `picard ValidateSamFile` did not throw an error either. Any ideas?

Thank you very much!

**Comment by JudithNeukamm** [comment]
Hi Alex, 
thanks for reporting this error. 
I also recognized this error, but have no solution at the moment. It only happened to me a few times, so I excluded these reads from generating the damage plot. However, this is NOT a proper solution. I'm working on this and will (hopefully) fix it in the next version. 
Best, Judith

**Comment by JudithNeukamm** [comment]
Hi Alex, 
Do you have a sample bam file where this problem occurs?

**Comment by alexhbnr** [comment]
I just checked and I currently cannot find the sample any longer or do not remember to which project it belonged. If I find it in the end, I will let you know. Sorry!

**Comment by JudithNeukamm** [comment]
Hi Alex, 
I could find a file where this issue occurs. Now, if this happens, the MD tag will be recalculated (reference file needed). In my case, the issue was solved then. 

I'll close this issue, but if you experience this error again, please let me know.
