### ISSUE TITLE
Add `--version` flag

### ISSUE THREAD

**Issue by jfy133** [Integrative-Transcriptomics/DamageProfiler#32]
It would be good for adding a flag that reports the current version of the tool, as this will make it easier for reproducibility (we require it in nf-core/eager, for example - see [issue](https://github.com/nf-core/eager/issues/237)).

**Comment by JudithNeukamm** [comment]
I added it and it will be included in the next version.

**Comment by jfy133** [comment]
@JudithNeukamm do you have an approximate ETA on when you would release the next version? We are readying up a major release of EAGER (2.1.0) in the next month or so and it would be helpful for me to know whether to use a hacky work-around for getting the version for MultiQC reporting.

**Comment by JudithNeukamm** [comment]
If it's that urgent, I can also release it now :) Give me 5 minutes.

**Comment by jfy133** [comment]
Depends on your definition of 'urgency' :laughing: . Like a said, a couple of months is fine - but thanks, much appreciated!

**Comment by JudithNeukamm** [comment]
:) No problem. Now, the flag is contained in version 0.4.8 (can be found under Releases).

**Comment by jfy133** [comment]
@JudithNeukamm Note that I think you didn't bump the version printed within DamageProfiler itself. I.e. you download release 0.4.8, but when running the `DamageProfiler-XXX.jar --version` the release version comes out as 0.4.7

**Comment by JudithNeukamm** [comment]
Oh yes, I totally forgot to change it there as well. I updated the version 0.4.8 in Releases.

**Comment by jfy133** [comment]
@apeltzer Does the autobump work for minor changes ?

**Comment by JudithNeukamm** [comment]
I updated it to version 0.4.9, so it should work :)

**Comment by apeltzer** [comment]
I did a rebump to do 0.4.8 but 0.4.9 should work and is better then I think :-) 
Thanks Judith!
