### ISSUE TITLE
Output folder wrong

### ISSUE THREAD

**Issue by lczech** [Integrative-Transcriptomics/DamageProfiler#45]
Hi there!

The documentation states that

> The results will directly be stored under the output folder specified with -o

See https://damageprofiler.readthedocs.io/en/latest/contents/generalUsage.html#how-to-run

However, when running DamageProfiler, instead, there is another directory created below the specified one, named after the input file without its sam/bam extension. I hope I didn't overlook a setting, but that is what I got.

I'd prefer if the tool actually behaved as documented, as this makes it easier to use in Snakemake and other pipeline tools.

Cheers and thanks
Lucas

**Comment by JudithNeukamm** [comment]
Hi Lucas, 

which version of DamageProfiler are you using? The documentation refers to version 1.0. The behaviour that you are describing was used in all versions before 1.0.
Thanks for pointing this out, I'll make it more clear in the docu. 
I hope this clarifies your question. 

Cheers, 
Judith

**Comment by lczech** [comment]
Hi Judith,

thanks for the quick reply. I'm using the latest [bioconda version](http://bioconda.github.io/recipes/damageprofiler/README.html), which is 0.5.0
Weird that 1.0 is not yet available there - doesn't that update automatically?

Cheers
Lucas

**Comment by jfy133** [comment]
Sorry @lczech it's been @apeltzer and I updating the conda recipe, I didn't get around to it yet - sorry. I will do that now!

**Comment by jfy133** [comment]
@JudithNeukamm should I wait for a point release with the fixed JSON output before bumping?

**Comment by JudithNeukamm** [comment]
@jfy133 I'll release a fixed version 1.1 today.

**Comment by lczech** [comment]
Thanks all! Ah okay, I see. I've never set up a bioconda recipe myself - and from what I knew I assumed that bioconda detects new versions automatically. Thanks for the clarification, and thanks for the quick fix!

**Comment by jfy133** [comment]
> Thanks all! Ah okay, I see. I've never set up a bioconda recipe myself - and from what I knew I assumed that bioconda detects new versions automatically. Thanks for the clarification, and thanks for the quick fix!

There are varying levels of automation but this can be shaky.

**Comment by JudithNeukamm** [comment]
@jfy133 Version 1.1 is released

**Comment by jfy133** [comment]
Bioconda PR: https://github.com/bioconda/bioconda-recipes/pull/24899 Hopefully straight forward!

**Comment by jfy133** [comment]
https://github.com/bioconda/bioconda-recipes/pull/24899 @lczech merged! Give it an hour or so and you'll hopefully be able to run aain with 1.1!

**Comment by lczech** [comment]
Thanks, that worked! :-)
