### ISSUE TITLE
Output format not recognized by MultiQC

### ISSUE THREAD

**Issue by lczech** [Integrative-Transcriptomics/DamageProfiler#46]
Hi there,

I am trying to integrate the DamageProfiler output into MultiQC, which does have a [fitting module](https://multiqc.info/docs/#damageprofiler). However, it seems that some number output format does not fit. I have already reported this in MultiQC, see https://github.com/ewels/MultiQC/issues/1318, but wanted to mention the issue here as well, just in case.

Feel free to close if this is not the appropriate place for reporting this.

Thanks and cheers
Lucas

**Comment by apeltzer** [comment]
Can you share the dmgprof.json file with us?

**Comment by JudithNeukamm** [comment]
Hi Lucas, 

for some reasons, I changed the length values to doubles. I will change it again. It should work then.

**Comment by JudithNeukamm** [comment]
@Alex: the file is available in the MultiQC issue that is linked.

**Comment by apeltzer** [comment]
> for some reasons, I changed the length values to doubles. I will change it again. It should work then.

Ok, that will then auto-fix itself so the multiqc issue can be closed I think ...?

**Comment by JudithNeukamm** [comment]
I think so, yes.

**Comment by lczech** [comment]
Thanks that sounds good. Any further questions/comments over at the [MultiQC issue](https://github.com/ewels/MultiQC/issues/1318) then ;-)

**Comment by lczech** [comment]
Just updated to version 1.1, everything works fine with MultiQC now! Thanks again!
