### ISSUE TITLE
How to create a valid bam file

### ISSUE THREAD

**Issue by Thomieh73** [Integrative-Transcriptomics/DamageProfiler#56]
Hi, I am trying to see if I can use this tool, but I get stopped at the moment I try to run the tool with the following error:

```
Welcome to DamageProfiler v1.1
        Input file:2-MOCK1-B-b_S145.mem.sorted.bam
        Output folder:DP_mock_results
Invalid SAM/BAM file. Please check your file.
```
In your documentation I am not able to find how to generate a valid bam file? Can you help me here?

Best Thomas

**Comment by apeltzer** [comment]
The DamageProfiler tool uses the HTSJDK libraries to parse SAM/BAM/CRAM input. As such, anything that is valid as in hts-spec is considered valid. https://github.com/samtools/htsjdk 

Maybe try validating your BAM file with this first: https://gatk.broadinstitute.org/hc/en-us/articles/360036351112-ValidateSamFile-Picard-

**Comment by Thomieh73** [comment]
Okay, thanks for answering. I will try it.
